config/routes.rb
Rails.application.routes.draw do
  root 'images#index'
  resources :images do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  validates :image, presence: true

  belongs_to :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :url, presence: true
  validates :title, presence: true
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  if Rails.env.production?
    protect_from_forgery with: :exception
  else
    protect_from_forgery with: :null_session
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    image = Image.find(params[:image_id])
    image.comments.create(params.require(:comment).permit(:body))
    respond_to do |format|
      format.html { redirect_to image_path(image) }
      format.json { head 201 }
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    Image.create(params.require(:image).permit(:url, :title))
    respond_to do |format|
      format.html { redirect_to action: :index }
      format.json { head 201 }
    end
  end

  def show
    @image = Image.find(params[:id])
  end

  def destroy
    Image.find(params[:id]).destroy
    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/index.html.haml
%h1
  画像一覧
%dl
  - @images.each do |image|
    %dt= image.title
    %dd
      = link_to image do
        = image_tag image.url
= link_to '画像を投稿する', new_image_path

app/views/images/new.html.haml
= form_for @image do |f|
  = f.label :title
  = f.text_field :title
  = f.label :url
  = f.text_field :url
  = f.submit

app/views/images/show.html.haml
%h1= @image.title
= image_tag @image.url
= link_to '削除', @image, method: :delete

%h2 コメント
%ur
  - @image.comments.each do |comment|
    %li
      = comment.body

= form_for [@image, Comment.new] do |f|
  = f.text_field :body
  = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bokete
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield